### ISSUE TITLE
`allOf` not collapsed when asserting "Array schema in a response has no maximum number of items defined"

### ISSUE THREAD

**Issue by caindy** [42Crunch/api-security-audit-action-freemium#3]
Hi, I'm running into an issue with [this validation](https://docs.42crunch.com/latest/content/oasv3/datavalidation/schema/v3-schema-response-array-maxitems.htm).

Here's an example of a schema that gets a false positive:
```yaml
type: object
additionalProperties: false
properties:
  transmission-facility-id:
    $ref: ./generic-identifier.yaml
  periods:
    allOf: 
      - $ref: ./constants/maximum-periods.yaml
      - type: array
        items:
          $ref: ./forecast-limit-period.yaml
```
where `./constant/maximum-periods.yaml` contains:
```yaml
maxItems: 240
```

I realize this is not so much an issue with the GH Action but the validation itself, so I hope this is an appropriate place to report the issue.

Thanks!
